name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Run tests
        run: |
          pio test

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Update version in library.properties
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Updating version to $VERSION in library.properties"
          sed -i "s/^version=.*/version=$VERSION/" library.properties

      - name: Create zip file
        run: zip -r SimpleLogger.zip SimpleLogger

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            SimpleLogger.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
