name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # add verify job
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Run tests
        run: |
          pio test

  # add build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build firmware
        run: |
          pio run
