name: Publish PlatformIO Package
#  add manual trigger

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger workflow only on tag pushes matching this pattern (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO CLI
      run: |
        python -m pip install -U platformio

    - name: Extract version from Git tag
      id: get_version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        if [ -z "$TAG_VERSION" ]; then
          echo "No tag found, using version 0.0.0"
          TAG_VERSION="0.0.0"
        fi
        echo "VERSION=${TAG_VERSION#v}" >> $GITHUB_ENV
        echo $VERSION

    - name: Update PlatformIO package version
      run: |
        VERSION=$(echo $VERSION)
        echo "Setting package version to $VERSION"
        sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" platformio.ini

    - name: Authenticate with PlatformIO
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: |
        echo $PLATFORMIO_AUTH_TOKEN | pio account login --token
        
    - name: Ensure PlatformIO username is set
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: | 
        pio account show || pio account update --username YOUR_USERNAME

    - name: Publish Package to PlatformIO
      env:
        PLATFORMIO_API_TOKEN: ${{ secrets.PLATFORMIO_API_TOKEN }}
      run: |
        pio pkg publish
